"""
build_transformations_report.py

Adds a "Transformations" sheet to the main lineage workbook, showing the raw
M code (and a deterministic, rule-based plain-English step breakdown) for
every hop of a table's lineage - the PBIX table's own query, its "reference
table" enumerator query (if any), the Level-1 dataflow entity, and the
Level-2/physical-source dataflow entity - matching the column layout of the
user-provided Cashplus-transformations.xlsx reference format.

The "AI command" columns are NOT generated by an LLM: they're produced by a
small rule-based M-step translator (see explain_m_steps()) covering the
common Power Query step vocabulary (Table.AddColumn, Table.DuplicateColumn,
Table.TransformColumnTypes, Table.SelectRows, connector navigation, etc.),
so results are deterministic, reproducible, and carry no hallucination risk.
Steps it doesn't recognize fall back to a generic "Applies transformation:
<raw step text>" line instead of guessing.
"""
import re

import lineage_lib as ll
from openpyxl.styles import PatternFill, Alignment, Font

HEADER_FILL = PatternFill(start_color="FF83CCEB", end_color="FF83CCEB", fill_type="solid")
GREEN_FILL = PatternFill(start_color="FFC6E0B4", end_color="FFC6E0B4", fill_type="solid")
RED_FILL = PatternFill(start_color="FFFF4B4B", end_color="FFFF4B4B", fill_type="solid")
GREY_FILL = PatternFill(start_color="FFD9D9D9", end_color="FFD9D9D9", fill_type="solid")
YELLOW_FILL = PatternFill(start_color="FFFFFF00", end_color="FFFFFF00", fill_type="solid")
WRAP = Alignment(wrap_text=True, vertical="top")

TRANSFORMATIONS_HEADERS = [
    "Color Code", "Entity Name in Source", "DTF 2 Transformation", "DTF 2 AI command",
    "DTF 1 Transformation", "DTF 1 AI command", "Reference Table Transformation",
    "Reference Table AI command", "Entity Transformation", "Entity AI command",
    "Entity Name in Report",
]

AI_DISCLAIMER = ("NOTE: This AI-generated transformation(AI command) is provided for reference "
                 "only; please refer to the original M Query transformation as the source of truth.")


# --------------------------------------------------------------------------
# Generic M `let ... in` step splitter (bracket/quote-depth aware, since RHS
# expressions routinely contain nested commas inside parens/brackets/braces -
# a plain regex/split(",") can't reliably tell steps apart).
# --------------------------------------------------------------------------
_STEP_NAME_RE = re.compile(r'\s*(#"(?:[^"\\]|\\.)*"|[A-Za-z_][\w]*)\s*=\s*')


def split_let_steps(text):
    """Return an ordered list of (step_name, rhs_text) for every top-level
    step inside the first `let ... in` block found in `text`. Returns []
    if no `let` block is present (e.g. a single-expression query)."""
    m = re.search(r'\blet\b', text or "")
    if not m:
        return []
    body = text[m.end():]
    steps = []
    i, n = 0, len(body)
    while i < n:
        while i < n and body[i] in " \t\r\n":
            i += 1
        if body[i:i + 2] == "in" and (i + 2 >= n or not (body[i + 2].isalnum() or body[i + 2] == '_')):
            break
        name_m = _STEP_NAME_RE.match(body, i)
        if not name_m:
            break
        name = ll.strip_quoted_ident(name_m.group(1))
        j = name_m.end()
        depth = 0
        in_str = False
        start = j
        while j < n:
            ch = body[j]
            if in_str:
                if ch == '"' and body[j - 1] != '\\':
                    in_str = False
            elif ch == '"':
                in_str = True
            elif ch in '([{':
                depth += 1
            elif ch in ')]}':
                depth -= 1
            elif depth == 0 and ch == ',':
                break
            elif depth == 0 and body[j:j + 2] == 'in' and not (body[j - 1].isalnum() or body[j - 1] == '_') and \
                    (j + 2 >= n or not (body[j + 2].isalnum() or body[j + 2] == '_')):
                break
            j += 1
        steps.append((name, body[start:j].strip()))
        i = j + 1 if j < n and body[j] == ',' else j
    return steps


# --------------------------------------------------------------------------
# Rule-based RHS -> plain-English description
# --------------------------------------------------------------------------
_RE_COLS_LIST = re.compile(r'\{([^{}]*)\}')


def _quoted_list(inner):
    return [ll.unquote(t) for t in re.findall(r'"(?:[^"\\]|\\.)*"', inner)]


def _describe_rhs(rhs):
    if re.search(r'Oracle\.Database\(', rhs):
        return "Connects to the Oracle database."
    if re.search(r'PowerPlatform\.Dataflows\(', rhs):
        return "Connects to all available Power Platform Dataflows."
    if re.search(r'SharePoint\.Files\(', rhs):
        return "Connects to a SharePoint document library."
    if re.search(r'Excel\.Workbook\(', rhs):
        return "Opens an Excel workbook."
    if re.search(r'Csv\.Document\(', rhs):
        return "Reads a CSV file."
    if re.search(r'Web\.Contents\(', rhs):
        return "Downloads content over HTTP."

    m = re.match(r'^.*?\{\[Schema\s*=\s*"([^"]+)"\]\}\[Data\]$', rhs)
    if m:
        return f"Selects the '{m.group(1)}' schema."
    m = re.match(r'^.*?\{\[(?:Name|Item)\s*=\s*"([^"]+)"\]\}\[Data\]$', rhs)
    if m:
        return f"Loads the '{m.group(1)}' table."
    m = re.match(r'^.*?\{\[entity\s*=\s*"([^"]+)"\]\}\[Data\]$', rhs)
    if m:
        return f"Selects the entity/table '{m.group(1)}'."
    m = re.match(r'^.*?\{\[Id\s*=\s*"([^"]+)"\]\}\[Data\]$', rhs)
    if m:
        return f"Navigates to the '{m.group(1)}' collection."
    m = re.match(r'^.*?\{\[workspaceId\s*=\s*"([^"]+)"\]\}\[Data\]$', rhs)
    if m:
        return f"Selects the workspace with ID '{m.group(1)}'."
    m = re.match(r'^.*?\{\[dataflowId\s*=\s*"([^"]+)"\]\}\[Data\]$', rhs)
    if m:
        return f"Selects the dataflow with ID '{m.group(1)}'."
    m = re.match(r'^.*?\{(\d+)\}\[Data\]$', rhs)
    if m:
        return f"Extracts record #{m.group(1)}'s Data."

    m = re.match(r'^Table\.SelectRows\(.*?,\s*each\s+(.*)\)$', rhs, re.DOTALL)
    if m:
        cond = m.group(1).strip()
        return f"Filters rows where {cond}." if len(cond) <= 200 else "Filters rows using a custom condition."

    m = re.match(r'^Table\.DuplicateColumn\([^,]+,\s*"([^"]+)"\s*,\s*"([^"]+)"', rhs)
    if m:
        return f"Creates '{m.group(2)}' as a duplicate of '{m.group(1)}'."

    m = re.match(r'^Table\.AddColumn\([^,]+,\s*"([^"]+)"\s*,\s*each\s+(.*)\)$', rhs, re.DOTALL)
    if m:
        new_col, body = m.group(1), m.group(2).strip()
        if len(body) <= 200:
            return f"Creates '{new_col}': {body}."
        return f"Creates '{new_col}' using a custom formula."

    if rhs.startswith("Table.TransformColumnTypes("):
        cols = re.findall(r'\{\s*"([^"]+)"\s*,', rhs)
        return f"Converts {', '.join(cols)} to their specified data types." if cols else \
            "Converts one or more columns to new data types."

    m = re.match(r'^Table\.RemoveColumns\([^,]+,\s*(\{.*\})\)$', rhs, re.DOTALL)
    if m:
        return f"Removes columns: {', '.join(_quoted_list(m.group(1)))}."

    m = re.match(r'^Table\.SelectColumns\([^,]+,\s*(\{.*\})\)$', rhs, re.DOTALL)
    if m:
        return f"Keeps only columns: {', '.join(_quoted_list(m.group(1)))}."

    m = re.match(r'^Table\.RenameColumns\([^,]+,\s*\{(.*)\}\)$', rhs, re.DOTALL)
    if m:
        pairs = re.findall(r'\{\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\}', m.group(1))
        return "Renames " + ", ".join(f"'{a}' \u2192 '{b}'" for a, b in pairs) + "." if pairs else \
            "Renames one or more columns."

    m = re.match(r'^Table\.CombineColumns\(.*?,\s*(\{[^{}]*\})\s*,.*?,\s*"([^"]+)"\)$', rhs, re.DOTALL)
    if m:
        return f"Combines {', '.join(_quoted_list(m.group(1)))} into '{m.group(2)}'."

    m = re.match(r'^Table\.ReplaceValue\([^,]+,\s*"([^"]*)"\s*,\s*"([^"]*)".*?,\s*(\{.*\})\)$', rhs, re.DOTALL)
    if m:
        return f"Replaces '{m.group(1)}' with '{m.group(2)}' in {', '.join(_quoted_list(m.group(3)))}."

    m = re.match(r'^Table\.ExpandTableColumn\([^,]+,\s*"([^"]+)"', rhs)
    if m:
        return f"Expands the nested table in column '{m.group(1)}'."

    if rhs.startswith("Table.Combine("):
        members = ll.extract_table_combine_members(rhs) or []
        return f"Combines multiple tables: {', '.join(members)}." if members else "Combines multiple tables."

    snippet = rhs if len(rhs) <= 150 else rhs[:150] + "..."
    return f"Applies transformation: {snippet}"


def explain_m_steps(m_text):
    """Return the 'Step\\tDescription\\n1. Name\\tDescription...' text block
    used for every '... AI command' column, or None if there's no M code to
    explain (e.g. no `let` block found)."""
    steps = split_let_steps(m_text)
    if not steps:
        return None
    lines = ["Step\tDescription"]
    for i, (name, rhs) in enumerate(steps, start=1):
        lines.append(f"{i}. {name}\t{_describe_rhs(rhs)}")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Per-row status bucket (Color Code column) - same priority order used for
# the main sheet's cell fills, kept in sync manually until that logic is
# consolidated into one shared helper.
# --------------------------------------------------------------------------
def _status_bucket(row):
    if not row.get("is_used", True):
        label, fill = "Tables not used in PBIX", RED_FILL
    elif row.get("hard_unresolved"):
        label, fill = "Unresolved / No Source Found", GREY_FILL
    elif row.get("needs_override"):
        label, fill = "Needs Manual Review", YELLOW_FILL
    elif row.get("status") == "found":
        label, fill = "Found Source Automatically", GREEN_FILL
    else:
        label, fill = "No M/Power Query Source", None
    return f"{label}\n\n{AI_DISCLAIMER}", fill


def _dataflow_query_text(ctx, stem, entity):
    df = ctx["dataflows"].get(stem)
    if not df:
        return None
    return df["queries"].get(entity)


def _with_dataflow_header(workspace, dataflow, entity, code):
    if code is None:
        return None
    header = f"WKS Name: {workspace},\nDataflow: {dataflow}\nEntity: {entity}\nDTF Transformation:\n"
    return header + code


# --------------------------------------------------------------------------
# Placeholder notes for the 4 raw-code columns - every blank cell must be
# self-explanatory (which of a small set of known, verified reasons applies),
# so a blank is never ambiguous between "deliberate" and "something's wrong".
# --------------------------------------------------------------------------
NOTE_FONT = Font(italic=True, color="FF808080")

NO_LINEAGE_NOTE = "[No dataflow source was resolved for this table - see Color Code / Remarks.]"


def _missing_dataflow_note(stem):
    return f"[Dataflow export file '{stem}' was not found in the provided folder.]"


def _no_query_note(ctx, stem, entity):
    """Explain why a dataflow's mashup document has no query text for this
    entity. Verified against real data: this is 100% correlated with the
    entity being a ReferenceEntity (a linked entity with no computed step of
    its own) - never a name-matching miss on a real (Local/Calculated) entity."""
    df = ctx["dataflows"].get(stem) or {}
    meta = df.get("entities", {}).get(entity)
    if meta is not None and meta.get("$type") == "ReferenceEntity":
        return (f"[Entity '{entity}' is a linked/reference entity in '{stem}' - it has no M code "
                "of its own; the actual transformation lives in the next dataflow hop shown below.]")
    return (f"[No matching M query found for entity '{entity}' in dataflow '{stem}' - "
            "please verify manually.]")


def _entity_name_in_source(phys, entity):
    """Structured 'where does this data physically live' breakdown, replacing
    the old single-value Talend-name lookup - format varies by connector
    type since each has a different notion of 'location'."""
    if not phys:
        return None
    connector = phys.get("connector")
    if connector == "Oracle Database":
        lines = []
        if phys.get("datamart"):
            lines.append(f"Datamart = {phys['datamart']}")
        if phys.get("schema"):
            lines.append(f'Schema = "{phys["schema"]}"')
        if phys.get("table") or entity:
            lines.append(f'Item = "{phys.get("table") or entity}"')
        return "\n".join(lines) if lines else None
    if connector in ("SharePoint Excel/CSV", "Excel Workbook", "Web Contents"):
        lines = []
        if phys.get("site"):
            lines.append(f"Site = {phys['site']}")
        if phys.get("folder"):
            lines.append(f"Folder = {phys['folder']}")
        if phys.get("file"):
            lines.append(f"File = {phys['file']}")
        return "\n".join(lines) if lines else None
    if phys.get("file"):
        return f"File = {phys['file']}"
    return entity


def _build_transformation_row(row, ctx):
    table = row["table"]
    entries = ctx["entries"]
    lvl1 = row.get("lvl1_raw")
    phys = row.get("phys")
    entity = row.get("entity")

    notes = set()

    entity_code = entries.get(table)
    if entity_code is None:
        entity_code = ("[No Power Query source for this table - likely a calculated table, "
                        "measures-only table, or parameter.]")
        notes.add("entity")

    reference_code = None
    reference_ai = None
    if lvl1 is None:
        reference_code = NO_LINEAGE_NOTE
        notes.add("reference")
    elif lvl1.get("path"):
        # Show every intermediate PBIX-level hop (not just the deepest one),
        # numbered in path order: "Reference Table 1" = closest to the table
        # itself, up to "Reference Table N" = the query that actually calls
        # PowerPlatform.Dataflows.
        code_blocks, ai_blocks = [], []
        for i, hop in enumerate(lvl1["path"], start=1):
            hop_code = entries.get(hop)
            if hop_code is None:
                hop_code = f"[No M code found for intermediate query '{hop}'.]"
            code_blocks.append(f"Reference Table {i}:\n{hop_code}")
            hop_ai = explain_m_steps(hop_code)
            if hop_ai:
                ai_blocks.append(f"Reference Table {i}:\n{hop_ai}")
        reference_code = "\n".join(code_blocks)
        reference_ai = "\n".join(ai_blocks) if ai_blocks else None
    else:
        reference_code = "[No separate reference-table hop - this table's query binds directly to the dataflow.]"
        notes.add("reference")

    dtf1_code = None
    dtf2_code = None

    if lvl1 is None or entity is None:
        dtf1_code = NO_LINEAGE_NOTE
        dtf2_code = NO_LINEAGE_NOTE
        notes.update(("dtf1", "dtf2"))
    else:
        dtf1_stem = lvl1["dataflow"]
        if dtf1_stem not in ctx["dataflows"]:
            dtf1_code = _missing_dataflow_note(dtf1_stem)
            notes.add("dtf1")
        else:
            dtf1_raw = _dataflow_query_text(ctx, dtf1_stem, entity)
            if dtf1_raw is None:
                dtf1_code = _no_query_note(ctx, dtf1_stem, entity)
                notes.add("dtf1")
            else:
                dtf1_code = _with_dataflow_header(lvl1["workspace"], dtf1_stem, entity, dtf1_raw)

        resolved_stem = (phys or {}).get("resolved_stem")
        if not resolved_stem:
            reason = (phys or {}).get("reason")
            dtf2_code = ("[No physical source could be resolved beyond DTF 1"
                          f"{f' - {reason}' if reason else ''}. See Remarks.]")
            notes.add("dtf2")
        elif resolved_stem == dtf1_stem:
            dtf2_code = ("[Single dataflow hop only - DTF 1 already contains the physical source; "
                         "no deeper hop exists.]")
            notes.add("dtf2")
        elif resolved_stem not in ctx["dataflows"]:
            dtf2_code = _missing_dataflow_note(resolved_stem)
            notes.add("dtf2")
        else:
            dtf2_raw = _dataflow_query_text(ctx, resolved_stem, entity)
            if dtf2_raw is None:
                dtf2_code = _no_query_note(ctx, resolved_stem, entity)
                notes.add("dtf2")
            else:
                dtf2_code = _with_dataflow_header(lvl1["workspace"], resolved_stem, entity, dtf2_raw)

    entity_name_in_source = _entity_name_in_source(phys, entity)

    label, fill = _status_bucket(row)

    return {
        "color_code": label, "fill": fill,
        "talend_name": entity_name_in_source,
        "dtf2_code": dtf2_code, "dtf2_ai": None if "dtf2" in notes else explain_m_steps(dtf2_code),
        "dtf1_code": dtf1_code, "dtf1_ai": None if "dtf1" in notes else explain_m_steps(dtf1_code),
        "reference_code": reference_code,
        "reference_ai": None if "reference" in notes else reference_ai,
        "entity_code": entity_code, "entity_ai": None if "entity" in notes else explain_m_steps(entity_code),
        "entity_name_report": table,
        "notes": notes,
    }


def add_transformations_sheet(wb, rows, ctx):
    """Append a 'Transformations' sheet to the given (already-populated)
    openpyxl Workbook, one row per PBIX table, matching the column layout of
    the Cashplus-transformations.xlsx reference format."""
    ws = wb.create_sheet("Transformations")

    for c, h in enumerate(TRANSFORMATIONS_HEADERS, start=1):
        cell = ws.cell(row=1, column=c, value=h)
        cell.fill = HEADER_FILL
        cell.font = Font(bold=True)

    r = 2
    for row in rows:
        t = _build_transformation_row(row, ctx)
        for c in range(1, len(TRANSFORMATIONS_HEADERS) + 1):
            ws.cell(row=r, column=c).alignment = WRAP

        ws.cell(row=r, column=1, value=t["color_code"])
        if t["fill"]:
            ws.cell(row=r, column=1).fill = t["fill"]
        ws.cell(row=r, column=2, value=t["talend_name"])
        ws.cell(row=r, column=3, value=t["dtf2_code"])
        ws.cell(row=r, column=4, value=t["dtf2_ai"])
        ws.cell(row=r, column=5, value=t["dtf1_code"])
        ws.cell(row=r, column=6, value=t["dtf1_ai"])
        ws.cell(row=r, column=7, value=t["reference_code"])
        ws.cell(row=r, column=8, value=t["reference_ai"])
        ws.cell(row=r, column=9, value=t["entity_code"])
        ws.cell(row=r, column=10, value=t["entity_ai"])
        ws.cell(row=r, column=11, value=t["entity_name_report"])

        for col, note_key in ((3, "dtf2"), (5, "dtf1"), (7, "reference"), (9, "entity")):
            if note_key in t["notes"]:
                ws.cell(row=r, column=col).font = NOTE_FONT
        r += 1

    widths = [16, 22, 45, 45, 45, 45, 45, 45, 45, 45, 22]
    for c, w in enumerate(widths, start=1):
        ws.column_dimensions[ws.cell(row=1, column=c).column_letter].width = w

    print(f"Transformations sheet: {len(rows)} rows written.")
